### ISSUE TITLE
Is your package working?

### ISSUE THREAD

**Issue by strictosensus** [YunoHost-Apps/osjs_ynh#1]
Your package is mark as 'NOT WORKING' on github

But mark as working on yunohost [package list](https://yunohost.org/#/apps_in_progress).

**Comment by frju365** [comment]
sorry... yes. My package is in development for instance. You can test it of course and give me feedback. It's is marked as NotWorking because I had no time to change it. But he is set on working... see the test on the CI jenkins to be sure. https://ci-apps.yunohost.org/jenkins/job/osjs%20(Community)/lastBuild/console
Just one recommendation : Don't install this package if you have already installed Etherpad_Mypads or if you have the intention to install it. There is an incompatibility in the installation of npm/nodejs which will solve in the next days.
Thanks for testing it or having an interest for it. In the next days I will create a new post about it on the forum.
frju365

**Comment by strictosensus** [comment]
No problem. In my opinion, package list must be update first to be sure to not do a mess.

i did'nt know yet os.js project. I regularly look at yunohost package list, and discover some new project.
os.js seem to be fun, a good chalenge.
I'm sorry about my poor feedback, I have to much things to test :S

**Comment by frju365** [comment]
All package in the package list are working but most of them are not ready for production. I've already test my package and it works. Just one thing is this npm installation. Don't worry if you have not time to test it, but this package has a big advantage : to have a desktop you can have access at any time, any moment with your folder/documents saved on it, just through a web browser. ;) A big post on the forum will "detail" it, you have a preview of it. :) Thanks ! :)
frju365

**Comment by frederikdyrmose** [comment]
I am very interested in this project, however, I use Etherpad_Mypads in my YunoHost installation. Have you fixed the incompatibility you talked about?

**Comment by frju365** [comment]
Apparently, fixed with the latest commit : 2281f70e84569a18eb26f1e7842f92d2f88b7bfc

osjs : level=2
